sudo: required
language: bash
os: osx

before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- openssl aes-256-cbc -K $encrypted_c7df9f3ece47_key -iv $encrypted_c7df9f3ece47_iv -in Unity_v2017.x.ulf.enc -out ./Unity_v2017.x.ulf -d

install:
- sudo -E sh ./Scripts/install.sh

script:
- sudo -E sh ./Scripts/build.sh
- rm Unity_v2017.x.ulf